// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi_VM2Ld40So_2IAr6WEtWFznLmUKTg4k',
    appId: '1:320283812493:web:d51cee2c4f26850ab9f8c4',
    messagingSenderId: '320283812493',
    projectId: 'home-service-76a7c',
    authDomain: 'home-service-76a7c.firebaseapp.com',
    storageBucket: 'home-service-76a7c.firebasestorage.app',
    measurementId: 'G-S977EEW5XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfMUPtS9FIS4-RfOlkNEMZQAYDSlF6qaM',
    appId: '1:320283812493:android:35b8a3eba0a21836b9f8c4',
    messagingSenderId: '320283812493',
    projectId: 'home-service-76a7c',
    storageBucket: 'home-service-76a7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX173AhJZPz_kbZjKgw21KXG2aZqumWtU',
    appId: '1:320283812493:ios:4f0e4c136c428024b9f8c4',
    messagingSenderId: '320283812493',
    projectId: 'home-service-76a7c',
    storageBucket: 'home-service-76a7c.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiHomeService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX173AhJZPz_kbZjKgw21KXG2aZqumWtU',
    appId: '1:320283812493:ios:4f0e4c136c428024b9f8c4',
    messagingSenderId: '320283812493',
    projectId: 'home-service-76a7c',
    storageBucket: 'home-service-76a7c.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiHomeService',
  );
}
